# 1. Información del Taller
site_name: Mis notas de FreeCAD
site_description: Mis notas sobre el uso de esta herramienta libre documentada utilizando la versión estable 0.20 de FreeCAD o bien alguna versión 0.21 Conda en desarrollo
site_author: Federico Coca
site_url: https://fgcoca.github.io/Mis-notas-de-FreeCAD/

# 2. Repositorio
repo_name: fgcoca/Mis-notas-de-FreeCAD
repo_url: https://github.com/fgcoca/Mis-notas-de-FreeCAD
edit_uri: ""

# 3. Copyright
copyright: Copyright &copy; 2022 - 2035 Federico Coca

# 4. RRSS
# extra:
#   social:
#     - icon: fontawesome/brands/twitter-square 
#       link: https://twitter.com/fgcoca
#       name: Twitter de Federico Coca
#     - icon: fontawesome/brands/github
#       link: https://github.com/fgcoca
#       name: Github de Federico Coca
#     - icon: fontawesome/brands/instagram
#       link: https://www.instagram.com/cocafederico/?hl=es
#       name: Instagram de Federico Coca
#     - icon: fontawesome/brands/twitter
#       link: https://twitter.com/clubroboticagra
#       name: Twitter de Club Robótica Granada 

# 5. Navegación
nav:
  - Preliminar: index.md
  - 1. Introducción: intro.md
  - 2. Banco de trabajo PartDesign: 2-PD.md
  - 2bis. Ampliación de PartDesign: 2bis-PD.md
  - 3. Planos de referencia:
    - 3.0. ¿Por qué debemos usar planos de referencia?: 3-porquePR.md
    - 3.1. Plano de referencia que pasa por tres puntos: 3-plano-ref.md
    - 3.2. Plano de referencia fijado a objeto: 3-PR-fijo-objeto.md
    - 3.3. Plano de referencia normal: 3-PR-normal.md
    - 3.4. Plano de referencia fijado a cara plana: 3-PR-fijo-cara-plana.md
    - 3.5. La propiedad Placement: 3-placement.md
  - 4. Diseño paramétrico en FreeCAD. Otros enfoques: 4-parametros.md
  - 5. Hojas de cálculo y datos dinámicos: 5-SPS-DD.md
  - 6. Dibujo técnico: 6-TD.md
  - 7. Tornillos y tuercas: 7-tornillos.md
  - 7bis. Ampliación tornillos y tuercas:
    - Banco de trabajo Fastener: bt_fastener.md
    - Banco de trabajo ThreadProfile: bt_ThreadProfile.md
  - 8. Edición de piezas 3D: 8-manipula.md
  - 9. Curvas en FreeCAD:
    - 9.1. Repaso de conceptos básicos sobre curvas en FreeCAD: 9_1-repaso-curvas.md
    - 9.2. B-Splines: 9_2-bsplines.md
    - 9.3. Banco de trabajo Curves: 9_3-curves.md
  - 10. Textos en FreeCAD:
    - Desde Draft: Texto/draft.md
    - Importar textos: Texto/importar.md
    - Texto sobre superficies curvas: Texto/tcurva.md
    - La macro FCCircularText: Texto/Macro_FCCircularText.md
  - Ejemplos resueltos:
    - Introducción: ejemplos/intro_ejemplos.md
    - Curves: ejemplos/ejem_curves.md
    - Ficha de empalme: ejemplos/ficha_em.md
    - Colección de ejemplos resueltos: ejemplos/coleccion.md
  - Miscelanea:
    - Autor: Miscelanea/about.md 
    - Licencias: Miscelanea/lic.md
    - Webgrafia/Bibliografía: Miscelanea/webgrafia.md
    - Software utilizado: Miscelanea/soft.md

# 6. Google Analytics
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto

# 7. Configuración del tema
theme:
  name: material
  # Color - Fuentes - Lenguaje
  palette:
    primary: light blue
    accent: deep purple 
  font:
    text: Roboto 
    code: Roboto Mono 
  logo: img/favicon.png 
  favicon: img/favicon.png 
  language: es
  extra:
    search:
      language: es, en
  # Página 404
  static_templates:
    - 404.html
  # No incluir los JavaScript de MkDocs
  #include_search_page: false
  #search_index_only: true

# 8. Extensiones
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      # guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# 9. Necesario para la extensión pydownx.arithmatex
extra_javascript:
  # Este fichero es opcional y solo si se quiere sobreescribir la configuracion del plugin
  #- js/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

# 10. Plugins
plugins:
  - search
  - minify:
      minify_html: true
